### PR TITLE
Logo design (revisited)

### PR DESCRIPTION
**Pull request by IfeanyiEkperi**
They are two options this time.

### CODE REVIEW

**Comment by shadowlion** [comment]
@IfeanyiEkperi, I was envisioning something like this:

rdf

only, not in a rasterized format (transparent background, .svg would be best) - I only need the brand in the upper left corner, so I'm not looking for a full-worded logo.

**Comment by IfeanyiEkperi** [comment]
Okay hope this would serve

**Comment by shadowlion** [comment]
@IfeanyiEkperi The first one looks good! I would still need it to have the following attributes:

- White font color
- SVG format
- transparent background

If those three things are met in the next commit, I'll merge the PR. Thanks!

**Comment by IfeanyiEkperi** [comment]
Please find attached the ZIP file containing the revised logo in transparent background SVG and PNG
[riverfront.zip](https://github.com/shadowlion/riverfront/files/3752853/riverfront.zip)

**Comment by shadowlion** [comment]
Solves #1. Well done, @IfeanyiEkperi

**Comment by IfeanyiEkperi** [comment]
Thank you @shadowlion It's always a pleasure contributing.

**Pull request merged**
